#!/bin/bash

mariadb -u root -p${MYSQL_ROOT_PASSWORD} << EOF
CREATE USER '$MARIADB_USER_TEST'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE_TEST;
GRANT ALL ON $MARIADB_DATABASE_TEST.* TO '$MARIADB_USER_TEST'@'%';
GRANT ALL ON $MARIADB_DATABASE_TEST.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
EOF
